# Generated by Django 5.0.1 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("export", "Exported"),
                            ("publish", "Published"),
                            ("archive", "Archived"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("scene", "Scene"),
                            ("shot", "Shot"),
                            ("call_sheet", "Call Sheet"),
                            ("continuity", "Continuity Note"),
                            ("cast_member", "Cast Member"),
                            ("equipment", "Equipment"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "activity_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
