# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("productions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="productions.production",
            ),
        ),
    ]
