# Generated by Django 5.0.1 on 2026-02-15 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productions", "0002_initial"),
        ("scenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hand_prop", "Hand Prop"),
                            ("set_dressing", "Set Dressing"),
                            ("vehicle", "Vehicle"),
                            ("weapon", "Weapon"),
                            ("food", "Food/Beverage"),
                            ("document", "Document/Paper"),
                            ("electronics", "Electronics"),
                            ("furniture", "Furniture"),
                            ("costume_prop", "Costume Prop"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needed", "Needed"),
                            ("sourced", "Sourced"),
                            ("purchased", "Purchased"),
                            ("rented", "Rented"),
                            ("ready", "Ready"),
                            ("on_set", "On Set"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="needed",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Where to get this prop", max_length=255
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_rented", models.BooleanField(default=False)),
                ("rental_return_date", models.DateField(blank=True, null=True)),
                ("brand_model", models.CharField(blank=True, max_length=255)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("size_dimensions", models.CharField(blank=True, max_length=100)),
                ("continuity_notes", models.TextField(blank=True)),
                (
                    "hero_prop",
                    models.BooleanField(
                        default=False, help_text="Is this a hero/featured prop?"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_props",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="props",
                        to="productions.production",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene where this prop is used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="props",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "db_table": "props",
                "ordering": ["category", "name"],
            },
        ),
    ]
