# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Production title", max_length=255
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, help_text="Director name", max_length=255
                    ),
                ),
                (
                    "production_company",
                    models.CharField(
                        blank=True, help_text="Production company name", max_length=255
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Production start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Production end date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre_production", "Pre-Production"),
                            ("production", "Production"),
                            ("post_production", "Post-Production"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pre_production",
                        help_text="Current production status",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total production budget",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Production description/synopsis"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        help_text="Genre (Drama, Action, Comedy, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "runtime_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected runtime in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        blank=True,
                        help_text="Aspect ratio (16:9, 2.35:1, etc.)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "production",
                "verbose_name_plural": "productions",
                "db_table": "productions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role in this specific production", max_length=100
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom permissions for this team member",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "production team member",
                "verbose_name_plural": "production team members",
                "db_table": "production_teams",
            },
        ),
    ]
