# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this production",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_productions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionteam",
            name="production",
            field=models.ForeignKey(
                help_text="Production this team member belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="productions.production",
            ),
        ),
        migrations.AddField(
            model_name="productionteam",
            name="user",
            field=models.ForeignKey(
                help_text="User who is part of this production",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(fields=["status"], name="productions_status_5729e7_idx"),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(
                fields=["created_by"], name="productions_created_a82ff7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(
                fields=["created_at"], name="productions_created_fce757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="production",
            index=models.Index(
                fields=["-created_at"], name="productions_created_26a892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionteam",
            index=models.Index(
                fields=["production"], name="production__product_eba5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionteam",
            index=models.Index(fields=["user"], name="production__user_id_e871cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productionteam",
            unique_together={("production", "user")},
        ),
    ]
