# Generated by Django 5.0.1 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("scenes_csv", "Scenes CSV"),
                            ("shots_csv", "Shots CSV"),
                            ("call_sheets_csv", "Call Sheets CSV"),
                            ("continuity_csv", "Continuity CSV"),
                            ("production_book_excel", "Production Book Excel"),
                            ("call_sheet_pdf", "Call Sheet PDF"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="Size in bytes", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "export_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
