# Generated by Django 5.0.1 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContinuityNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("costume", "Costume"),
                            ("props", "Props"),
                            ("makeup", "Makeup"),
                            ("hair", "Hair"),
                            ("set_dressing", "Set Dressing"),
                            ("lighting", "Lighting"),
                            ("camera", "Camera"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("actor_character", models.CharField(blank=True, max_length=255)),
                ("specific_details", models.JSONField(blank=True, default=dict)),
                ("warnings", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("flagged", "Flagged"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "continuity_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
