# Generated by Django 5.0.1 on 2026-02-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("continuity", "0002_initial"),
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="continuitynote",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="continuitynote",
            name="shot",
        ),
        migrations.RemoveField(
            model_name="continuitynote",
            name="specific_details",
        ),
        migrations.RemoveField(
            model_name="continuitynote",
            name="title",
        ),
        migrations.AlterField(
            model_name="continuitynote",
            name="actor_character",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="continuitynote",
            name="category",
            field=models.CharField(
                choices=[
                    ("costume", "Costume"),
                    ("props", "Props"),
                    ("makeup", "Makeup"),
                    ("hair", "Hair"),
                    ("lighting", "Lighting"),
                    ("camera", "Camera"),
                    ("script", "Script"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="continuitynote",
            name="scene",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="continuity_notes",
                to="scenes.scene",
            ),
        ),
        migrations.AlterField(
            model_name="continuitynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("flagged", "Flagged"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
