# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shot_number", models.CharField(db_index=True, max_length=20)),
                ("shot_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "shot_type",
                    models.CharField(
                        choices=[
                            ("WIDE", "Wide Shot"),
                            ("MEDIUM", "Medium Shot"),
                            ("CLOSE_UP", "Close-Up"),
                            ("EXTREME_CLOSE_UP", "Extreme Close-Up"),
                            ("TWO_SHOT", "Two Shot"),
                            ("OVER_SHOULDER", "Over Shoulder"),
                            ("POV", "Point of View"),
                            ("INSERT", "Insert"),
                            ("ESTABLISHING", "Establishing Shot"),
                            ("MASTER", "Master Shot"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "camera_angle",
                    models.CharField(
                        choices=[
                            ("EYE_LEVEL", "Eye Level"),
                            ("HIGH_ANGLE", "High Angle"),
                            ("LOW_ANGLE", "Low Angle"),
                            ("DUTCH_ANGLE", "Dutch Angle"),
                            ("AERIAL", "Aerial"),
                            ("BIRDS_EYE", "Birds Eye"),
                        ],
                        default="EYE_LEVEL",
                        max_length=20,
                    ),
                ),
                (
                    "camera_movement",
                    models.CharField(
                        choices=[
                            ("STATIC", "Static"),
                            ("PAN", "Pan"),
                            ("TILT", "Tilt"),
                            ("DOLLY", "Dolly"),
                            ("TRACKING", "Tracking"),
                            ("CRANE", "Crane"),
                            ("HANDHELD", "Handheld"),
                            ("STEADICAM", "Steadicam"),
                            ("ZOOM", "Zoom"),
                        ],
                        default="STATIC",
                        max_length=20,
                    ),
                ),
                ("camera_model", models.CharField(blank=True, max_length=100)),
                (
                    "lens",
                    models.CharField(
                        blank=True, help_text="e.g., 50mm, 24-70mm", max_length=50
                    ),
                ),
                ("focal_length", models.CharField(blank=True, max_length=20)),
                (
                    "aperture",
                    models.CharField(
                        blank=True, help_text="e.g., f/2.8", max_length=10
                    ),
                ),
                ("iso", models.CharField(blank=True, max_length=10)),
                (
                    "frame_rate",
                    models.IntegerField(default=24, help_text="Frames per second"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("takes_planned", models.IntegerField(default=1)),
                ("takes_completed", models.IntegerField(default=0)),
                ("best_take", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("vfx_required", models.BooleanField(default=False)),
                ("vfx_notes", models.TextField(blank=True)),
                ("sound_notes", models.TextField(blank=True)),
                ("lighting_setup", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("sequence_order", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="Scene this shot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shots",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "db_table": "shots",
                "ordering": ["sequence_order", "shot_number"],
                "unique_together": {("scene", "shot_number")},
            },
        ),
        migrations.CreateModel(
            name="Take",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("take_number", models.IntegerField()),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("issues", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takes",
                        to="shots.shot",
                    ),
                ),
            ],
            options={
                "db_table": "takes",
                "ordering": ["take_number"],
                "unique_together": {("shot", "take_number")},
            },
        ),
    ]
