# Generated by Django 5.0.1 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shoot_date", models.DateField(db_index=True)),
                (
                    "day_number",
                    models.IntegerField(
                        blank=True, help_text="Shooting day number", null=True
                    ),
                ),
                ("call_time", models.TimeField()),
                ("crew_call_time", models.TimeField(blank=True, null=True)),
                ("wrap_time_estimate", models.TimeField(blank=True, null=True)),
                ("location_address", models.TextField(blank=True)),
                ("parking_info", models.TextField(blank=True)),
                ("weather_forecast", models.CharField(blank=True, max_length=255)),
                ("sunrise_time", models.TimeField(blank=True, null=True)),
                ("sunset_time", models.TimeField(blank=True, null=True)),
                ("meals_provided", models.JSONField(blank=True, default=list)),
                ("nearest_hospital", models.TextField(blank=True)),
                ("safety_notes", models.TextField(blank=True)),
                ("general_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In Progress"),
                            ("wrapped", "Wrapped"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "call_sheets",
                "ordering": ["-shoot_date"],
            },
        ),
        migrations.CreateModel(
            name="CallSheetCast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_time", models.TimeField()),
                ("pickup_location", models.CharField(blank=True, max_length=255)),
                ("makeup_time", models.TimeField(blank=True, null=True)),
                ("scenes_today", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("on_set", "On Set"),
                            ("wrapped", "Wrapped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "call_sheet_cast",
            },
        ),
        migrations.CreateModel(
            name="CallSheetScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                ("sequence_order", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "call_sheet_scenes",
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("character_name", models.CharField(blank=True, max_length=255)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("supporting", "Supporting"),
                            ("day_player", "Day Player"),
                            ("extra", "Extra"),
                            ("stunt", "Stunt"),
                        ],
                        default="supporting",
                        max_length=20,
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cast_members",
                "ordering": ["name"],
            },
        ),
    ]
