# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("call_sheets", "0001_initial"),
        ("productions", "0001_initial"),
        ("scenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callsheet",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_call_sheets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callsheet",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sheets",
                to="productions.production",
            ),
        ),
        migrations.AddField(
            model_name="callsheetcast",
            name="call_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast",
                to="call_sheets.callsheet",
            ),
        ),
        migrations.AddField(
            model_name="callsheetscene",
            name="call_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="call_sheets.callsheet",
            ),
        ),
        migrations.AddField(
            model_name="callsheetscene",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scenes.scene"
            ),
        ),
        migrations.AddField(
            model_name="castmember",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cast_members",
                to="productions.production",
            ),
        ),
        migrations.AddField(
            model_name="callsheetcast",
            name="cast_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="call_sheets.castmember"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="callsheetscene",
            unique_together={("call_sheet", "scene")},
        ),
    ]
