# Generated by Django 5.0.1 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("scenes_completed", models.IntegerField(default=0)),
                ("shots_completed", models.IntegerField(default=0)),
                (
                    "pages_shot",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_progress",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_scenes", models.IntegerField(default=0)),
                ("completed_scenes", models.IntegerField(default=0)),
                ("in_progress_scenes", models.IntegerField(default=0)),
                ("not_started_scenes", models.IntegerField(default=0)),
                ("total_shots", models.IntegerField(default=0)),
                ("completed_shots", models.IntegerField(default=0)),
                (
                    "total_script_pages",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("shooting_days", models.IntegerField(default=0)),
                ("days_completed", models.IntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("team_size", models.IntegerField(default=0)),
                ("cast_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Production Statistics",
                "db_table": "production_statistics",
            },
        ),
    ]
