# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("productions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprogress",
            name="production",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_progress",
                to="productions.production",
            ),
        ),
        migrations.AddField(
            model_name="productionstatistics",
            name="production",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="productions.production",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyprogress",
            unique_together={("production", "date")},
        ),
    ]
