# Generated by Django 5.0.1 on 2026-02-14 19:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_number",
                    models.CharField(
                        db_index=True,
                        help_text="Scene number from script (e.g., '1', '2A', '15')",
                        max_length=20,
                    ),
                ),
                (
                    "scene_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional scene name or slug line",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Scene description or action"
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True,
                        help_text="Location description (e.g., 'COFFEE SHOP', 'PARK')",
                        max_length=255,
                    ),
                ),
                (
                    "interior_exterior",
                    models.CharField(
                        choices=[
                            ("INT", "Interior"),
                            ("EXT", "Exterior"),
                            ("INT/EXT", "Interior/Exterior"),
                        ],
                        default="INT",
                        help_text="Interior or Exterior",
                        max_length=10,
                    ),
                ),
                (
                    "day_night",
                    models.CharField(
                        choices=[
                            ("DAY", "Day"),
                            ("NIGHT", "Night"),
                            ("DAWN", "Dawn"),
                            ("DUSK", "Dusk"),
                            ("CONTINUOUS", "Continuous"),
                        ],
                        default="DAY",
                        help_text="Time of day",
                        max_length=15,
                    ),
                ),
                (
                    "script_pages",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Number of script pages (e.g., 2.5)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Actual duration filmed in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="not_started",
                        help_text="Current scene status",
                        max_length=20,
                    ),
                ),
                (
                    "shooting_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Scheduled shooting date",
                        null=True,
                    ),
                ),
                (
                    "call_time",
                    models.TimeField(
                        blank=True, help_text="Call time for this scene", null=True
                    ),
                ),
                (
                    "wrap_time",
                    models.TimeField(
                        blank=True, help_text="Actual wrap time", null=True
                    ),
                ),
                (
                    "cast_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of cast members required (JSON array)",
                    ),
                ),
                (
                    "crew_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of crew positions required (JSON array)",
                    ),
                ),
                (
                    "equipment_needed",
                    models.TextField(
                        blank=True, help_text="Equipment needed for this scene"
                    ),
                ),
                (
                    "special_effects",
                    models.TextField(blank=True, help_text="Special effects notes"),
                ),
                (
                    "stunts_required",
                    models.BooleanField(
                        default=False, help_text="Indicates if stunts are required"
                    ),
                ),
                (
                    "vfx_required",
                    models.BooleanField(
                        default=False, help_text="Indicates if VFX is required"
                    ),
                ),
                (
                    "weather_dependent",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if scene is weather dependent",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about the scene"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Priority level (higher = more important)"
                    ),
                ),
                (
                    "sequence_order",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order in which scene appears in script",
                    ),
                ),
                (
                    "script_day",
                    models.CharField(
                        blank=True,
                        help_text="Script day (e.g., 'Day 1', 'Night 2')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "production",
                    models.ForeignKey(
                        help_text="Production this scene belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="productions.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "scene",
                "verbose_name_plural": "scenes",
                "db_table": "scenes",
                "ordering": ["sequence_order", "scene_number"],
                "indexes": [
                    models.Index(
                        fields=["production"], name="scenes_product_a7d620_idx"
                    ),
                    models.Index(fields=["status"], name="scenes_status_fb20bf_idx"),
                    models.Index(
                        fields=["shooting_date"], name="scenes_shootin_1ec5ad_idx"
                    ),
                    models.Index(
                        fields=["sequence_order"], name="scenes_sequenc_af9240_idx"
                    ),
                    models.Index(
                        fields=["production", "status"],
                        name="scenes_product_41734a_idx",
                    ),
                ],
                "unique_together": {("production", "scene_number")},
            },
        ),
    ]
